### ISSUE TITLE
ClassNotFoundException: ConfigurationBeanFactoryMetadata

### ISSUE THREAD

**Issue by gitgabrio** [stratospheric-dev/stratospheric#95]
### What's going wrong and not working?

Dear sirs,
I've cloned the repo  https://github.com/stratospheric-dev/stratospheric.git, opened inside IntelliJ, gone in the 
`getting-started-with-spring-boot-on-aws` directory and, after setting up AWS stuff, I issued the command:
`./gradlew bootRun`
but I get the following exception
`Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata`
Not sure if it is something related to this page https://spring.io/projects/spring-cloud `Table 1. Release train Spring Boot compatibility`

Best Regards

Gabriele

**Comment by rieckpil** [comment]
Thanks for reporting this, we'll take a look at it.

**Comment by rieckpil** [comment]
Thanks again for giving us a hint on the failing application startup. I could reproduce it and as you mentioned it's caused by an incompatibility issue. I've migrated the application to awspring (see reason [here](https://maciejwalkowiak.com/blog/spring-cloud-aws-2-3-rc2-released/)) and it's now working again (double checked it locally and also added a basic startup integration test).

Changes are integrated to the `main` branch: https://github.com/stratospheric-dev/stratospheric/commit/5345ebe71cf2bf02700c125382d2c9455dc0d9f4

**Comment by gitgabrio** [comment]
Great! Thanks @rieckpil
